// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/rate.proto

package rate_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ask           float64                `protobuf:"fixed64,2,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_proto_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{1}
}

func (x *RateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RateResponse) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *RateResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *RateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_rate_proto protoreflect.FileDescriptor

const file_proto_rate_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rate.proto\x12\x04rate\"-\n" +
	"\x0fGetRatesRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\"|\n" +
	"\fRateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\x01R\x03bid\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency2D\n" +
	"\vRateService\x125\n" +
	"\bGetRates\x12\x15.rate.GetRatesRequest\x1a\x12.rate.RateResponseB\tZ\arate.pbb\x06proto3"

var (
	file_proto_rate_proto_rawDescOnce sync.Once
	file_proto_rate_proto_rawDescData []byte
)

func file_proto_rate_proto_rawDescGZIP() []byte {
	file_proto_rate_proto_rawDescOnce.Do(func() {
		file_proto_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rate_proto_rawDesc), len(file_proto_rate_proto_rawDesc)))
	})
	return file_proto_rate_proto_rawDescData
}

var file_proto_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rate_proto_goTypes = []any{
	(*GetRatesRequest)(nil), // 0: rate.GetRatesRequest
	(*RateResponse)(nil),    // 1: rate.RateResponse
}
var file_proto_rate_proto_depIdxs = []int32{
	0, // 0: rate.RateService.GetRates:input_type -> rate.GetRatesRequest
	1, // 1: rate.RateService.GetRates:output_type -> rate.RateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rate_proto_init() }
func file_proto_rate_proto_init() {
	if File_proto_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rate_proto_rawDesc), len(file_proto_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rate_proto_goTypes,
		DependencyIndexes: file_proto_rate_proto_depIdxs,
		MessageInfos:      file_proto_rate_proto_msgTypes,
	}.Build()
	File_proto_rate_proto = out.File
	file_proto_rate_proto_goTypes = nil
	file_proto_rate_proto_depIdxs = nil
}
