services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=currency_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres_rates:
        condition: service_healthy

  postgres_rates:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=currency_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5  

volumes:
  postgres_data:
  